"""Link UserSettings to User model and add unique constraint

Revision ID: 29730976a2ef
Revises: c61e655ae461
Create Date: 2025-06-04 16:57:41.034302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29730976a2ef'
down_revision = 'c61e655ae461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Provide explicit names for constraints
        batch_op.create_unique_constraint('uq_user_settings_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_user_settings_user_id_user',
                                   'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_settings_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('uq_user_settings_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
